require('andrewgil')
local Plug = vim.fn['plug#']

vim.call('plug#begin')
-- Language Server related plugins
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/vim-vsnip')
Plug('hrsh7th/cmp-vsnip')
Plug('https://github.com/Hoffs/omnisharp-extended-lsp.nvim.git')
Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
-- searching
Plug('ibhagwan/fzf-lua')
Plug('junegunn/fzf')
Plug('kokusenz/deltaview.nvim', {branch = 'feature/delta-lua-integration'})
Plug('kokusenz/delta.lua')
Plug('MunifTanjim/nui.nvim')
Plug('esmuellert/codediff.nvim')
Plug('josephschmitt/pj.nvim')
-- nice to haves
Plug('stevearc/oil.nvim')
Plug('fabijanzulj/blame.nvim')
-- color schemes
Plug('sainnhe/gruvbox-material')
Plug('lifepillar/vim-solarized8')
Plug('shaunsingh/nord.nvim')
Plug('catppuccin/nvim')
Plug('folke/tokyonight.nvim')
Plug('bluz71/vim-moonfly-colors')
Plug('rose-pine/neovim', {['as'] = 'rose-pine'})
-- ai lol
Plug('olimorris/codecompanion.nvim')
Plug('ravitemer/codecompanion-history.nvim')
Plug('zbirenbaum/copilot.lua')
Plug('nvim-lua/plenary.nvim')
vim.call('plug#end')

require('statusline')
require('colorscheme')
require('searching')
require('lsp')
require('make')
require('blametoggle')
require('fzf').setup_fzf_lua()
require('vimuiselect').setup()
require('oil').setup()
require('pj_config')
