vim.cmd.packadd('nvim.difftool')
vim.cmd.packadd('cfilter')
local config = vim.fn.stdpath('config')
vim.opt.rtp:remove(config)
vim.opt.rtp:remove(config .. '/after')
package.path = config .. '/lua/?.lua;' .. config .. '/lua/?/init.lua;' .. package.path
require('preferences')
require('conveniences')
require('statusline')
require('tabline')
require('searching')
require('jj')
