local c = require('config')
c.setup()
c.preferences()
c.conveniences()
c.statusline()
c.tabline()
c.searching()
c.jujutsu()
c.cfilter()
-- todo add colorscheme, but after we figure out how to best lazy load schemes that aren't default in config
