vim.cmd([[cabbrev dm DeltaMenu]])
vim.cmd([[cabbrev dv DeltaView]])
vim.cmd([[cabbrev da Delta . 3]])

local config = require('config')
config.create_user_command(config.options.keyconfig.glance_delta, true, function(cmd_opts)
    local lines = table.concat(vim.api.nvim_buf_get_lines(0, cmd_opts.line1 - 1, cmd_opts.line2, false), '\n')
    local win, _ = require('floating').new_popup('center')
    local delta = require('delta')
    local bufnr = delta.patch_diff(lines, true)
    if bufnr == nil then return end
    vim.api.nvim_win_set_buf(win, bufnr)
    vim.schedule(function() delta.highlight_delta_artifacts(bufnr) end)
    vim.schedule(function() delta.syntax_highlight_diff_set(bufnr) end)
    vim.schedule(function() delta.diff_highlight_diff(bufnr) end)
end)
